apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dominion-db-pvc
  namespace: default
spec:
  storageClassName: ""
  volumeName: dominion-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
